services:
  search-service:
    container_name: sapp
    image: search-service:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - CONFIG_SERVER_URL=http://172.17.0.1:8888
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - my-network
  elasticsearch:
    container_name: esearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    restart: on-failure
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-network
networks:
  my-network:
    external: true
volumes:
  esdata: